### ISSUE TITLE
导出的模型不支持动态宽高

### ISSUE THREAD

**Issue by cqray1990** [thb1314/maskrcnn-tensorrt#2]
如果导出动态宽高，就会出错，单独导出动态batch的可能行
 dynamic_axes = {
                input_name: {
                    0: 'batch',
                    2：'H',
                   3: 'w'
                },
                'dets': {
                    0: 'batch',
                    1: 'num_dets',
                },
                'labels': {
                    0: 'batch',
                    1: 'num_dets',
                },
            }

**Comment by thb1314** [comment]
@cqray1990 你可以不去覆盖为动态batch所做的工作，这样就会支持动态宽高了。

**Comment by cqray1990** [comment]
> @cqray1990 你可以不去覆盖为动态batch所做的工作，这样就会支持动态宽高了。

不覆盖为动态batch什么意思？ 我已经改了 导出输入的格式，

input_name: {
0: 'batch',
2：'H',
3: 'w'
},
2，3维都是动态的，导出失败，提示Shape不对，我试过动态batch，和宽高导出不行

**Comment by thb1314** [comment]
@cqray1990 

> > @cqray1990 你可以不去覆盖为动态batch所做的工作，这样就会支持动态宽高了。
> 
> 不覆盖为动态batch什么意思？ 我已经改了 导出输入的格式，
> 
> input_name: { 0: 'batch', 2：'H', 3: 'w' }, 2，3维都是动态的，导出失败，提示Shape不对，我试过动态batch，和宽高导出不行


[六. 动态batch的支持](https://github.com/thb1314/maskrcnn-tensorrt#%E5%85%AD-%E5%8A%A8%E6%80%81batch%E7%9A%84%E6%94%AF%E6%8C%81)

这一个章节的工作都不做，然后对比覆盖代码，凡是有h和w维度的操作都取消掉

**Comment by cqray1990** [comment]
> @cqray1990
> 
> > > @cqray1990 你可以不去覆盖为动态batch所做的工作，这样就会支持动态宽高了。
> > 
> > 
> > 不覆盖为动态batch什么意思？ 我已经改了 导出输入的格式，
> > input_name: { 0: 'batch', 2：'H', 3: 'w' }, 2，3维都是动态的，导出失败，提示Shape不对，我试过动态batch，和宽高导出不行
> 
> [六. 动态batch的支持](https://github.com/thb1314/maskrcnn-tensorrt#%E5%85%AD-%E5%8A%A8%E6%80%81batch%E7%9A%84%E6%94%AF%E6%8C%81)
> 
> 这一个章节的工作都不做，然后对比覆盖代码，凡是有h和w维度的操作都取消掉

@thb1314 还是导出失败，H，W 变成 -1 ，就会导致推理的shape不对

**Comment by thb1314** [comment]
@cqray1990 这里H和W维度都需要取shape维度，而且不加入int()这样的强制类型转换。

**Comment by cqray1990** [comment]
> @cqray1990 这里H和W维度都需要取shape维度，而且不加入int()这样的强制类型转换。

@thb1314 
博主可以再push一个动态H，W的转换？

**Comment by thb1314** [comment]
@cqray1990 用爱发电，实在抱歉，短期内不会。

**Comment by thb1314** [comment]
如果实在需要，请联系 zhuilewang@163.com 进一步交流

**Comment by thb1314** [comment]
@cqray1990  如果实在需要，请联系 [zhuilewang@163.com](mailto:zhuilewang@163.com) 进一步交流
